apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-quotes-app
  name: movie-quotes-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: movie-quotes-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: movie-quotes-app
    spec:
      containers:
      - image: europe-west4-docker.pkg.dev/learning-kubernetes-348509/hello-repo/movie-quote-app:0.4-amd64
        imagePullPolicy: IfNotPresent
        name: movie-quote-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
