apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-quotes-app
  name: movie-quotes-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: movie-quotes-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-quotes-app
    spec:
      containers:
      - image: movie-quotes-app:0.4-aarch64
        imagePullPolicy: IfNotPresent
        name: movie-quote-app
        ports:
          - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-quotes-app
  name: movie-quotes-app-service
  namespace: default
spec:
  selector:
    app: movie-quotes-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      nodePort: 30201
      targetPort: 3000
  type: NodePort
